apiVersion: v2
name: webapp
description: A Helm chart for your web application

# This is the chart version
version: 0.1.0

# This is the version of the application being deployed
appVersion: "1.0.0"

dependencies:
  - name: redis
    version: "17.x.x"
    repository: "https://charts.bitnami.com/bitnami"

# Add these lines to include the common templates
type: application
