service:
  type: ClusterIP
  port: 80

redis:
  enabled: true
  auth:
    enabled: true
    password: "redis-password"
  architecture: standalone
  hooks:
    master:
      init:
        enabled: true

# Hooks configuration
hooks:
  dbInit:
    enabled: false
    image: your-db-init-image:tag
    command: []
    args: []

backup:
  enabled: true

connectionTest:
  enabled: true

config:
  redis:
    host: "webapp-redis-master"
    port: 6379
  env:
    APP_ENV: production
    DEBUG: "false"
  features:
    - metrics
    - logging
    - tracing

app: Release.Name

global:
  configMapName: "webapp-newconfig"
  storageClass: "standard"
  redis:
    password: "redis-password"

persistence:
  enabled: true

backupPVC:
  size: 1Gi
  storageClassName: standard

tests:
  enabled: false
  persistence:
    enabled: true
