{{- if and .Values.redis.enabled .Values.redis.hooks.master.init.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}-redis-init"
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    spec:
      containers:
      - name: redis-init
        image: redis:latest
        command: ['sh', '-c', 'redis-cli -h {{ .Values.config.redis.host }} -p {{ .Values.config.redis.port }} -a {{ .Values.redis.auth.password }} CONFIG SET maxmemory-policy allkeys-lru']
      restartPolicy: Never
  backoffLimit: 1
{{- end }}
