{{- if .Values.redis.enabled }}
{{- template "validate.service" . }}
apiVersion: v1
kind: Service
metadata:
  name: webapp
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      protocol: TCP
      name: http
  selector: {{- include "appDef" . | nindent 4 }}
{{- end }}
